import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Smasherson Tour",
  description: "Generated by create next app",
  keywords: "smasherson, tour, smashersontour",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
        <body className={[inter.className]}>
          <NavBar />
          {children}
        </body>
      </html>
  );
}
